package com.kliq.app.ui.theme

import androidx.compose.ui.graphics.Color

val PurplePrimary = Color(0xFF8B5CF6)
val PurplePrimaryDark = Color(0xFF6D28D9)
val PurplePrimaryLight = Color(0xFFC084FC)
val PurpleContainer = Color(0xFF4C1D95)
val PurpleContainerLight = Color(0xFFEDE9FE)
val OnPurpleContainer = Color(0xFFEDE9FE)
val OnPurpleContainerLight = Color(0xFF1E0A3C)

val TealSecondary = Color(0xFF14B8A6)
val TealSecondaryDark = Color(0xFF0F766E)
val TealSecondaryLight = Color(0xFF5EEAD4)
val TealContainer = Color(0xFF134E4A)
val TealContainerLight = Color(0xFFCCFBF1)
val OnTealContainer = Color(0xFFCCFBF1)
val OnTealContainerLight = Color(0xFF042F2E)

val FuchsiaTertiary = Color(0xFFD946EF)
val FuchsiaTertiaryDark = Color(0xFFA21CAF)
val FuchsiaTertiaryLight = Color(0xFFF0ABFC)
val FuchsiaContainer = Color(0xFF701A75)
val FuchsiaContainerLight = Color(0xFFFAE8FF)
val OnFuchsiaContainer = Color(0xFFFAE8FF)
val OnFuchsiaContainerLight = Color(0xFF4A044E)

val ErrorRed = Color(0xFFEF4444)
val ErrorRedDark = Color(0xFFDC2626)
val ErrorRedLight = Color(0xFFFCA5A5)
val ErrorContainer = Color(0xFF7F1D1D)
val ErrorContainerLight = Color(0xFFFEE2E2)
val OnErrorContainer = Color(0xFFFEE2E2)
val OnErrorContainerLight = Color(0xFF450A0A)

val DarkBackground = Color(0xFF0C0914)
val DarkSurface = Color(0xFF161124)
val DarkSurfaceVariant = Color(0xFF241C38)
val DarkSurfaceContainer = Color(0xFF1C162E)
val DarkSurfaceContainerHigh = Color(0xFF281F3D)
val DarkSurfaceContainerHighest = Color(0xFF352B4E)
val DarkOutline = Color(0xFF8B7BB0)
val DarkOutlineVariant = Color(0xFF6B5C8A)
val DarkOnBackground = Color(0xFFF5F3FF)
val DarkOnSurface = Color(0xFFEDE9FE)
val DarkOnSurfaceVariant = Color(0xFFDDD6FE)
val DarkInverseSurface = Color(0xFFEDE9FE)
val DarkInverseOnSurface = Color(0xFF161124)
val DarkInversePrimary = Color(0xFF6D28D9)
val DarkScrim = Color(0xFF000000)

val LightBackground = Color(0xFFFCFAFF)
val LightSurface = Color(0xFFF8F5FF)
val LightSurfaceVariant = Color(0xFFEDE9FE)
val LightSurfaceContainer = Color(0xFFF3EEFF)
val LightSurfaceContainerHigh = Color(0xFFEDE9FE)
val LightSurfaceContainerHighest = Color(0xFFE4DEFA)
val LightOutline = Color(0xFF7C7494)
val LightOutlineVariant = Color(0xFFC4BCD6)
val LightOnBackground = Color(0xFF1A1523)
val LightOnSurface = Color(0xFF1A1523)
val LightOnSurfaceVariant = Color(0xFF4A4358)
val LightInverseSurface = Color(0xFF2D2640)
val LightInverseOnSurface = Color(0xFFF3EEFF)
val LightInversePrimary = Color(0xFFBB86FC)
val LightScrim = Color(0xFF000000)

val HighContrastPurplePrimary = Color(0xFFC084FC)
val HighContrastBackground = Color(0xFF000000)
val HighContrastSurface = Color(0xFF121212)
val HighContrastSurfaceVariant = Color(0xFF1F1B2E)
val HighContrastOnBackground = Color(0xFFFFFFFF)
val HighContrastOnSurface = Color(0xFFFFFFFF)
val HighContrastOutline = Color(0xFFA855F7)
